### ISSUE TITLE
Layers appear on map which are not named in "Visible Map Layer" box

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/sinangoe-webmap#12]
The map which appears in the preview view seems to show everything which is visible on the mapbox map at that zoom level (depending upon how the computer displays it with the bounds that are set). So this results in some layers appearing on the preview map even if they are not mentioned in the Visible Map Layer box in the CMS.

See image below where the thin black lines are pipelines, which I have just added to the Mapbox map as a new layer. They are not mentioned in the CMS box, however they appear on the preview. 

<img width="1280" alt="Screenshot 2020-04-29 at 11 48 53" src="https://user-images.githubusercontent.com/21277147/80588107-9bb9a980-8a0f-11ea-8d18-cebd89dfd4e0.png">

<img width="1280" alt="Screenshot 2020-04-29 at 11 49 03" src="https://user-images.githubusercontent.com/21277147/80588093-952b3200-8a0f-11ea-9bee-7d8a3e99fe55.png">

<img width="1280" alt="Screenshot 2020-04-29 at 11 49 41" src="https://user-images.githubusercontent.com/21277147/80588077-8e042400-8a0f-11ea-80f4-d4b0fb055a24.png">

I actually do want them to appear, but was not able to choose them as the CMS box had not yet refreshed to include them as an option - so this particular instance of this bug isn't a problem, and I will add them as a layer when the system refreshes, however it seems to indicate a more general problem, as according to how I understand the CMS, this layer ought not appear unless named.

**Comment by okdistribute** [comment]
i think this will be fixed by the code in #12

**Comment by okdistribute** [comment]
Ok, I believe this should be fixed now [by this code](https://github.com/digidem/sinangoe-webmap/blob/d28c8d84e91afc36c24f475c26d4bc3da293e7e1/src/admin/layer-picker/control.js#L116) but I haven't had time to thoroughly test it.

**Comment by aliya-ryan** [comment]
Hi - this issue is not yet fixed. If a layer is switched on in the MB style, then it appears on the sinangoe-mapa.ddem.us preview whether or not it is specifically named to appear in the CMS.
I can show some examples of this if it's not clear what I mean, but would be easier to do via a screenshare than uploading screenshots.

**Comment by okdistribute** [comment]
Yeah, it would be very helpful for me to see inside what you have in Mapbox and what's not appearing because it's quite difficult to work in a vacuum. Let's hop on a call?

**Comment by okdistribute** [comment]
Also I wonder if you're still seeing this issue now?
